name: iOS CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Run SwiftLint
      run: swiftlint
      
    - name: Build and run tests
      run: xcodebuild test -scheme Swiftee -destination 'platform=iOS Simulator,name=iPhone 11' -enableCodeCoverage YES | xcpretty

    - name: Generate coverage report
      run: |
        xcrun llvm-cov export -format=lcov -instr-profile ./DerivedData/Build/Products/Debug-iphonesimulator/codecov.profdata ./DerivedData/Build/Products/Debug-iphonesimulator/Swiftee.app/Swiftee > coverage_report.info

    - name: Verify test coverage
      run: |
        COVERAGE=$(xcrun llvm-cov report -instr-profile ./DerivedData/Build/Products/Debug-iphonesimulator/codecov.profdata ./DerivedData/Build/Products/Debug-iphonesimulator/Swiftee.app/Swiftee | grep "TOTAL" | awk '{print $4}' | sed 's/%//')
        if (( $(echo "$COVERAGE < 75" | bc -l) )); then
          echo "Test coverage is below 75% ($COVERAGE%)"
          exit 1
        fi

    - name: Upload coverage report to Codecov
      run: bash <(curl -s https://codecov.io/bash) -f coverage_report.info
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: Swiftee/test-results
