name: Swift

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch: 
  
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: swift build -v
      working-directory: ./Swiftee
    - name: Run tests
      run: swift test -v
      working-directory: ./Swiftee
